import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "@/assets/theme/theme";
import "./globals.scss";
import { ThemeProvider } from "@mui/material";
import { AppProvider } from "@/context/productList";
import { TestimonialsProvider } from "@/context/testimonialsContext";
import { CartProvider } from "@/context/cartContext";
import { AddressProvider } from "@/context/addressContext";
import { AuthAppProvider } from "@/context/authContext";
import {
  GlobalLoader,
  LoaderProvider,
  useLoader,
} from "@/context/loaderContext";
import Loader from "@/components/Loader";
import { OrderContextProvider } from "@/context/ordersContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LoaderProvider>
          <AuthAppProvider>
            <AppProvider>
              <CartProvider>
                <AddressProvider>
                  <OrderContextProvider>
                    <TestimonialsProvider>
                      {children}
                      <GlobalLoader />
                    </TestimonialsProvider>
                  </OrderContextProvider>
                </AddressProvider>
              </CartProvider>
            </AppProvider>
          </AuthAppProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
