import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "@/assets/theme/theme";
import "./globals.scss";
import { ThemeProvider } from "@mui/material";
import { AppProvider } from "@/context/productList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
